# this var indicates if the target is a physical machine
# so that we can adjust certain settings accordingly
baremetal: false
install_omz: false

# empty means autodetect from the running session; set to xfce or mate to force
desktop_environment: ""