---
- name: Copy templates to ~/Templates
  ansible.builtin.copy:
    src: Templates/
    dest: "{{ ansible_facts['env']['HOME'] }}/Templates/"
    mode: '0644'
  tags:
    - desktop
    - templates

- name: Include XFCE appearance settings
  import_tasks: xfce.yml
  tags:
    - desktop
    - appearance
    - xfce
