---
- name: common dotfiles tasks preparation
  import_tasks: common.yml
  tags:
    - dotfiles
    - common

- name: deploy dotfiles via symlinks
  import_tasks: symlinks.yml
  when: dotfiles_use_symlinks | default(true) | bool
  tags:
    - dotfiles
    - symlinks

- name: deploy dotfiles via copying
  import_tasks: copy.yml
  when: not (dotfiles_use_symlinks | default(true) | bool)
  tags:
    - dotfiles
    - copy
