---
- name: configure user sudoers
  import_tasks: user.yml
  tags:
    - system
    - user

- name: configure system keyboard layout
  import_tasks: keyboard.yml
  tags:
    - system
    - keyboard

- name: configure system timezone
  import_tasks: timezone.yml
  tags:
    - system
    - timezone

- name: install system scripts
  import_tasks: scripts.yml
  tags:
    - system
    - scripts