---
- name: install burpsuite
  import_tasks: burpsuite.yml
  tags:
    - firefox-burpsuite
    - burpsuite

- name: configure firefox
  import_tasks: firefox.yml
  tags:
    - firefox-burpsuite
    - firefox