---
install_pyenv: true

go_releases_url: "https://go.dev/dl/?mode=json"
go_install_tools: false

nvim_repo_url: "https://github.com/neovim/neovim.git"
nvim_build_dir: "/tmp/neovim"
nvim_build_type: "RelWithDebInfo"
