---
- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
    autoclean: true
  become: true

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - autorecon
      - bettercap
      - binwalk
      - build-essential
      - commix
      - copyq
      - curl
      - exiftool
      - exploitdb
      - fzf
      - ghidra
      - git
      - gitk
      - gobuster
      - hexedit
      - htop
      - jadx
      - jq
      - libpcap-dev
      - ltrace
      - moreutils
      - nodejs
      - nfs-common
      - npm
      - python3-pip
      - ranger
      - ripgrep
      - rlwrap
      - rofi
      - seclists
      - stow
      - vim
      - xsel
      - zoxide
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Remove unused apt packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true
