---
- name: remove apt version of go
  apt:
    name: [golang, golang-go]
    state: absent
    purge: true
  become: true

- name: check installed go version
  command: /usr/local/go/bin/go version
  register: go_check
  failed_when: false
  changed_when: false

- name: install go
  when: go_check.rc != 0 or go_version not in go_check.stdout
  block:
    - name: download and extract go
      unarchive:
        src: "{{ go_download_url }}"
        dest: /usr/local
        remote_src: true
      become: true

    - name: symlink go binaries
      file:
        src: "/usr/local/go/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
      become: true
      loop: [go, gofmt]
