---
- name: install apt tools
  import_tasks: apt.yml
  tags:
    - tools
    - apt

- name: install docker
  import_tasks: docker.yml
  tags:
    - tools
    - docker

- name: install python tools
  import_tasks: python.yml
  tags:
    - tools
    - python

- name: install ruby gems
  import_tasks: gems.yml
  tags:
    - tools
    - gems

- name: install golang
  import_tasks: golang.yml
  tags:
    - tools
    - golang

- name: install wireshark
  import_tasks: wireshark.yml
  tags:
    - tools
    - wireshark

- name: install neovim
  import_tasks: nvim.yml
  tags:
    - tools
    - nvim

# - name: install bloodhound
#   import_tasks: bloodhound.yml
#   tags:
#     - tools
#     - bloodhound

- name: install binary ninja
  import_tasks: binaryninja.yml
  tags:
    - tools
    - binaryninja

- name: install shelf
  import_tasks: shelf.yml
  tags:
    - tools
    - shelf
