---
- import_tasks: apt.yml
  tags:
    - tools
    - apt

- import_tasks: docker.yml
  tags:
    - tools
    - docker

- import_tasks: python.yml
  tags:
    - tools
    - python

- import_tasks: gems.yml
  tags:
    - tools
    - gems

- import_tasks: golang.yml
  tags:
    - tools
    - golang

- import_tasks: wireshark.yml
  tags:
    - tools
    - wireshark

- import_tasks: nvim.yml
  tags:
    - tools
    - nvim

- import_tasks: bloodhound.yml
  tags:
    - tools
    - bloodhound

- import_tasks: binaryninja.yml
  tags:
    - tools
    - binaryninja
